### PR TITLE
Deploy to cloud bug fix

### PR DESCRIPTION
**Pull request by sanjeevghimire**

### CODE REVIEW

**Comment by stevemart** [comment]
@sanjeevghimire can you update the commit message to describe how you fixed the bug? And also include the text `Closes: #55` so it's linked to the bug.

**Comment by sanjeevghimire** [comment]
@stevemart   commit message amended.

**Comment by scottdangelo** [comment]
OK, I think the message is in one of the commits.

**Comment by sanjeevghimire** [comment]
This PR fixes/closes #55 . The issue is to do with dev dependencies not installed when pushing to cloudfoundry using `ibmcloud` cli.

The project use Typescript. Node.js doesn't understand typescript directly, so it has to be compiled into JavaScript first using `tsc` command and then run the built project. Since typescript is added as a devDependency in `package.json`, relying on Cloud Foundry to install the dependency didn't work.

The solution was to build the project before you push to IBM cloud. The steps are:
* Run `npm run build` locally which creates a `dist` directory with compiles source files.
* copy `package.json` to the `dist` folder
* Push to IBM cloud and run `server.js`.

**Pull request merged**
